In [19]:
!pip install numpy==2.4.3

In [14]:
import numpy as np

In [15]:
## x0
x0 = np.array([[0.35],
                [0.25],
                [0.40]])
print(x0)
print(x0.shape)


[[0.35]
 [0.25]
 [0.4 ]]
(3, 1)


In [16]:
# transition matrix
A = np.array([[0.65, 0.15, 0.20],
                [0.25, 0.70, 0.25],
                [0.10, 0.15, 0.55]])
print(A.shape)
print(A)

(3, 3)
[[0.65 0.15 0.2 ]
 [0.25 0.7  0.25]
 [0.1  0.15 0.55]]


In [17]:
## (a)
def calc_matrix(A, x, n):
    for calc in range(n):
        x = np.matmul(A, x)
    return x

def vals_m(x):
    labels = ["O", "P", "Q"]
    for i in range(len(x)):
        return "\n".join([f"{labels[i]}: {round(x[i][0], 2)}" for i in range(len(x))])

x12 = calc_matrix(A, x0, 12)
x24 = calc_matrix(A, x0, 24)

print("Market Distribution after 1 year:\n{}".format(vals_m(x12)))
print("Market Distribution after 2 years:\n{}".format(vals_m(x24)))


Market Distribution after 1 year:
O: 0.32
P: 0.45
Q: 0.22
Market Distribution after 2 years:
O: 0.32
P: 0.45
Q: 0.22


In [18]:
## (b)
# By considering only customers in Q, we can say that the new matrix would be q0 = [[0],[0],[1]]
# Because we're looking only into this subgroup within the entire market
q0 = np.array([[0],
               [0],
               [1]])

q2 = calc_matrix(A, q0, 2)
print("Market Distribution after the second month:\n{}".format(vals_m(q2)))

Market Distribution after the second month:
O: 0.28
P: 0.36
Q: 0.36
