In [2]:
!pip install numpy==2.4.3

In [3]:
import numpy as np

In [4]:
## x0
x0 = np.array([[0.35],
                [0.25],
                [0.40]])
print(x0)
print(x0.shape)


[[0.35]
 [0.25]
 [0.4 ]]
(3, 1)


In [5]:
# transition matrix
A = np.array([[0.65, 0.15, 0.20],
                [0.25, 0.70, 0.25],
                [0.10, 0.15, 0.55]])
print(A.shape)
print(A)

(3, 3)
[[0.65 0.15 0.2 ]
 [0.25 0.7  0.25]
 [0.1  0.15 0.55]]


In [6]:
## (a)
def calc_matrix(A, x, n):
    for calc in range(n):
        x = np.matmul(A, x)
    return x

def vals_m(x):
    labels = ["O", "P", "Q"]
    for i in range(len(x)):
        return "\n".join([f"{labels[i]}: {round(x[i][0], 2)}" for i in range(len(x))])

x12 = calc_matrix(A, x0, 12)
x24 = calc_matrix(A, x0, 24)

print("Market Distribution after 1 year:\n{}".format(vals_m(x12)))
print("Market Distribution after 2 years:\n{}".format(vals_m(x24)))


Market Distribution after 1 year:
O: 0.32
P: 0.45
Q: 0.22
Market Distribution after 2 years:
O: 0.32
P: 0.45
Q: 0.22


In [7]:
## (b)
# By considering only customers in Q, we can say that the new matrix would be q0 = [[0],[0],[1]]
# Because we're looking only into this subgroup within the entire market
q0 = np.array([[0],
               [0],
               [1]])

q2 = calc_matrix(A, q0, 2)
print("Market Distribution after the second month:\n{}".format(vals_m(q2)))

Market Distribution after the second month:
O: 0.28
P: 0.36
Q: 0.36


In [8]:
#c)
# %%
## (c)

# long-term
x_long = calc_matrix(A, x0, 100)

print("Market distribution after many periods (long run):\n{}".format(vals_m(x_long)))

# trying with different conditions
x0_O = np.array([[1.0], [0.0], [0.0]])
x0_M = np.array([[0.0], [1.0], [0.0]])
x0_Q = np.array([[0.0], [0.0], [1.0]])

x_O = calc_matrix(A, x0_O, 100)
x_M = calc_matrix(A, x0_M, 100)
x_Q = calc_matrix(A, x0_Q, 100)

print("\nLong run starting from O:\n{}".format(vals_m(x_O)))
print("\nLong run starting from M:\n{}".format(vals_m(x_M)))
print("\nLong run starting from Q:\n{}".format(vals_m(x_Q)))

Market distribution after many periods (long run):
O: 0.32
P: 0.45
Q: 0.22

Long run starting from O:
O: 0.32
P: 0.45
Q: 0.22

Long run starting from M:
O: 0.32
P: 0.45
Q: 0.22

Long run starting from Q:
O: 0.32
P: 0.45
Q: 0.22
